import os
import re

"""
create_config.py

Reads `.env` in the project folder and writes `config.js` that sets
window.__GROQ_API_KEY and optional window.__GROQ_MODEL for the frontend.

Usage:
  python create_config.py

This script does not print the key. It writes `config.js` which should be
added to `.gitignore` (already recommended).
"""

HERE = os.path.dirname(__file__)
env_path = os.path.join(HERE, '.env')
config_path = os.path.join(HERE, 'config.js')

if not os.path.exists(env_path):
    print('.env file not found. Create .env with GROQ_API_KEY and optionally GROQ_MODEL.')
    raise SystemExit(1)

key = None
model = None
with open(env_path, 'r', encoding='utf-8') as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        m = re.match(r'^GROQ_API_KEY=(.*)$', line)
        if m:
            key = m.group(1).strip()
            if (key.startswith('"') and key.endswith('"')) or (key.startswith("'") and key.endswith("'")):
                key = key[1:-1]
            continue
        m2 = re.match(r'^GROQ_MODEL=(.*)$', line)
        if m2:
            model = m2.group(1).strip()
            if (model.startswith('"') and model.endswith('"')) or (model.startswith("'") and model.endswith("'")):
                model = model[1:-1]

if not key:
    print('GROQ_API_KEY not found in .env')
    raise SystemExit(1)

model_js = model if model else ''

content_lines = [
    '// This file is generated by create_config.py and contains sensitive data.\n',
    '// Do NOT commit this file to version control.\n',
    f'window.__GROQ_API_KEY = "{key}";\n',
]
if model_js:
    content_lines.append(f'window.__GROQ_MODEL = "{model_js}";\n')

with open(config_path, 'w', encoding='utf-8') as f:
    f.writelines(content_lines)

print('Wrote config.js (contains API key). Keep this file private.')
